/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTraceUsersRouteImport } from './routes/_app/trace-users'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as AppObservationsRouteImport } from './routes/_app/observations'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppGrantsRouteImport } from './routes/_app/grants'
import { Route as AppAccessRouteImport } from './routes/_app/access'
import { Route as AppTracesIndexRouteImport } from './routes/_app/traces.index'
import { Route as AppConfigurationIndexRouteImport } from './routes/_app/configuration/index'
import { Route as AuthOpenidCallbackRouteImport } from './routes/auth/openid/callback'
import { Route as AppTracesTraceIdRouteImport } from './routes/_app/traces.$traceId'
import { Route as AppSessionsSessionIdRouteImport } from './routes/_app/sessions.$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTraceUsersRoute = AppTraceUsersRouteImport.update({
  id: '/trace-users',
  path: '/trace-users',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppObservationsRoute = AppObservationsRouteImport.update({
  id: '/observations',
  path: '/observations',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppGrantsRoute = AppGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppTracesIndexRoute = AppTracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigurationIndexRoute = AppConfigurationIndexRouteImport.update({
  id: '/configuration/',
  path: '/configuration/',
  getParentRoute: () => AppRoute,
} as any)
const AuthOpenidCallbackRoute = AuthOpenidCallbackRouteImport.update({
  id: '/auth/openid/callback',
  path: '/auth/openid/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTracesTraceIdRoute = AppTracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => AppSessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/grants': typeof AppGrantsRoute
  '/help': typeof AppHelpRoute
  '/observations': typeof AppObservationsRoute
  '/sessions': typeof AppSessionsRouteWithChildren
  '/trace-users': typeof AppTraceUsersRoute
  '/users': typeof AppUsersRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/traces/$traceId': typeof AppTracesTraceIdRoute
  '/auth/openid/callback': typeof AuthOpenidCallbackRoute
  '/configuration/': typeof AppConfigurationIndexRoute
  '/traces/': typeof AppTracesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/grants': typeof AppGrantsRoute
  '/help': typeof AppHelpRoute
  '/observations': typeof AppObservationsRoute
  '/sessions': typeof AppSessionsRouteWithChildren
  '/trace-users': typeof AppTraceUsersRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/traces/$traceId': typeof AppTracesTraceIdRoute
  '/auth/openid/callback': typeof AuthOpenidCallbackRoute
  '/configuration': typeof AppConfigurationIndexRoute
  '/traces': typeof AppTracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/grants': typeof AppGrantsRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/observations': typeof AppObservationsRoute
  '/_app/sessions': typeof AppSessionsRouteWithChildren
  '/_app/trace-users': typeof AppTraceUsersRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/_app/traces/$traceId': typeof AppTracesTraceIdRoute
  '/auth/openid/callback': typeof AuthOpenidCallbackRoute
  '/_app/configuration/': typeof AppConfigurationIndexRoute
  '/_app/traces/': typeof AppTracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access'
    | '/grants'
    | '/help'
    | '/observations'
    | '/sessions'
    | '/trace-users'
    | '/users'
    | '/sessions/$sessionId'
    | '/traces/$traceId'
    | '/auth/openid/callback'
    | '/configuration/'
    | '/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/access'
    | '/grants'
    | '/help'
    | '/observations'
    | '/sessions'
    | '/trace-users'
    | '/users'
    | '/'
    | '/sessions/$sessionId'
    | '/traces/$traceId'
    | '/auth/openid/callback'
    | '/configuration'
    | '/traces'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/access'
    | '/_app/grants'
    | '/_app/help'
    | '/_app/observations'
    | '/_app/sessions'
    | '/_app/trace-users'
    | '/_app/users'
    | '/_app/'
    | '/_app/sessions/$sessionId'
    | '/_app/traces/$traceId'
    | '/auth/openid/callback'
    | '/_app/configuration/'
    | '/_app/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthOpenidCallbackRoute: typeof AuthOpenidCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trace-users': {
      id: '/_app/trace-users'
      path: '/trace-users'
      fullPath: '/trace-users'
      preLoaderRoute: typeof AppTraceUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/observations': {
      id: '/_app/observations'
      path: '/observations'
      fullPath: '/observations'
      preLoaderRoute: typeof AppObservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grants': {
      id: '/_app/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof AppGrantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/traces/': {
      id: '/_app/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof AppTracesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuration/': {
      id: '/_app/configuration/'
      path: '/configuration'
      fullPath: '/configuration/'
      preLoaderRoute: typeof AppConfigurationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/openid/callback': {
      id: '/auth/openid/callback'
      path: '/auth/openid/callback'
      fullPath: '/auth/openid/callback'
      preLoaderRoute: typeof AuthOpenidCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/traces/$traceId': {
      id: '/_app/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof AppTracesTraceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$sessionId': {
      id: '/_app/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppSessionsRoute
    }
  }
}

interface AppSessionsRouteChildren {
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRoute
}

const AppSessionsRouteChildren: AppSessionsRouteChildren = {
  AppSessionsSessionIdRoute: AppSessionsSessionIdRoute,
}

const AppSessionsRouteWithChildren = AppSessionsRoute._addFileChildren(
  AppSessionsRouteChildren,
)

interface AppRouteChildren {
  AppAccessRoute: typeof AppAccessRoute
  AppGrantsRoute: typeof AppGrantsRoute
  AppHelpRoute: typeof AppHelpRoute
  AppObservationsRoute: typeof AppObservationsRoute
  AppSessionsRoute: typeof AppSessionsRouteWithChildren
  AppTraceUsersRoute: typeof AppTraceUsersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTracesTraceIdRoute: typeof AppTracesTraceIdRoute
  AppConfigurationIndexRoute: typeof AppConfigurationIndexRoute
  AppTracesIndexRoute: typeof AppTracesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessRoute: AppAccessRoute,
  AppGrantsRoute: AppGrantsRoute,
  AppHelpRoute: AppHelpRoute,
  AppObservationsRoute: AppObservationsRoute,
  AppSessionsRoute: AppSessionsRouteWithChildren,
  AppTraceUsersRoute: AppTraceUsersRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppTracesTraceIdRoute: AppTracesTraceIdRoute,
  AppConfigurationIndexRoute: AppConfigurationIndexRoute,
  AppTracesIndexRoute: AppTracesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthOpenidCallbackRoute: AuthOpenidCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
